-- MySQL Script generated by MySQL Workbench
-- Mon Aug 13 18:13:28 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema DB_faculdade
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema DB_faculdade
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `DB_faculdade` DEFAULT CHARACTER SET utf8 ;
USE `DB_faculdade` ;

-- -----------------------------------------------------
-- Table `DB_faculdade`.`Departamento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Departamento` (
  `Cod_Departamento` INT NULL,
  `Nome_Departamento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_Departamento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Professor` (
  `Cod_Professor` INT NOT NULL,
  `Cod_Departamento` INT NOT NULL,
  `Nome_Professor` VARCHAR(45) NOT NULL,
  `Sobrenome_Professor` VARCHAR(45) NOT NULL,
  `Status` BLOB NOT NULL,
  PRIMARY KEY (`Cod_Professor`, `Cod_Departamento`),
  INDEX `Cod_Deparatamento_idx` (`Cod_Departamento` ASC),
  CONSTRAINT `Cod_Deparatamento`
    FOREIGN KEY (`Cod_Departamento`)
    REFERENCES `DB_faculdade`.`Departamento` (`Cod_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Disciplina` (
  `Cod_Disciplina` INT NOT NULL,
  `Cod_Departamento` INT NOT NULL,
  `Nome_Disciplina` VARCHAR(45) NOT NULL,
  `Descricao` VARCHAR(45) NOT NULL,
  `Num_Alunos` INT NOT NULL,
  `Carga_Horaria` INT NOT NULL,
  PRIMARY KEY (`Cod_Disciplina`, `Cod_Departamento`),
  INDEX `Cod_Departamento_idx` (`Cod_Departamento` ASC),
  CONSTRAINT `Cod_Departamento`
    FOREIGN KEY (`Cod_Departamento`)
    REFERENCES `DB_faculdade`.`Departamento` (`Cod_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Prof_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Prof_Disciplina` (
  `Cod_Professor` INT NOT NULL,
  `Cod_Disciplina` INT NOT NULL,
  PRIMARY KEY (`Cod_Professor`, `Cod_Disciplina`),
  INDEX `Cod_Disciplina_idx` (`Cod_Disciplina` ASC),
  CONSTRAINT `Cod_Professor`
    FOREIGN KEY (`Cod_Professor`)
    REFERENCES `DB_faculdade`.`Professor` (`Cod_Professor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_Disciplina`
    FOREIGN KEY (`Cod_Disciplina`)
    REFERENCES `DB_faculdade`.`Disciplina` (`Cod_Disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Curso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Curso` (
  `Cod_Curso` INT NOT NULL,
  `Cod_Departamento` INT NOT NULL,
  `Nome_Curso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_Curso`, `Cod_Departamento`),
  INDEX `Cod_Departamento_idx` (`Cod_Departamento` ASC),
  CONSTRAINT `Cod_Departamento`
    FOREIGN KEY (`Cod_Departamento`)
    REFERENCES `DB_faculdade`.`Departamento` (`Cod_Departamento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Curso_Disciplina`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Curso_Disciplina` (
  `Cod_Disciplina` INT NOT NULL,
  `Cod_Curso` INT NOT NULL,
  PRIMARY KEY (`Cod_Disciplina`, `Cod_Curso`),
  INDEX `Cod_Curso_idx` (`Cod_Curso` ASC),
  CONSTRAINT `Cod_Disciplina`
    FOREIGN KEY (`Cod_Disciplina`)
    REFERENCES `DB_faculdade`.`Disciplina` (`Cod_Disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_Curso`
    FOREIGN KEY (`Cod_Curso`)
    REFERENCES `DB_faculdade`.`Curso` (`Cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Turma`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Turma` (
  `Cod_Turma` INT NOT NULL,
  `Cod_Curso` INT NOT NULL,
  `Num_Alunos` VARCHAR(45) NOT NULL,
  `Periodo` VARCHAR(45) NOT NULL,
  `Data_Inicio` DATE NOT NULL,
  `Data_Fim` DATE NOT NULL,
  PRIMARY KEY (`Cod_Turma`, `Cod_Curso`),
  INDEX `Cod_Cruso_idx` (`Cod_Curso` ASC),
  CONSTRAINT `Cod_Cruso`
    FOREIGN KEY (`Cod_Curso`)
    REFERENCES `DB_faculdade`.`Curso` (`Cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Aluno` (
  `Cod_Aluno` INT NOT NULL,
  `Cod_Curso` INT NOT NULL,
  `Cod_Turma` INT NOT NULL,
  `Nome_Aluno` VARCHAR(45) NOT NULL,
  `Sobrenome_Aluno` VARCHAR(45) NOT NULL,
  `Sexo` VARCHAR(45) NOT NULL,
  `CPF` VARCHAR(45) NOT NULL,
  `Status` BLOB NOT NULL,
  PRIMARY KEY (`Cod_Aluno`, `Cod_Curso`, `Cod_Turma`),
  INDEX `Cod_Curso_idx` (`Cod_Curso` ASC),
  INDEX `Cod_Turma_idx` (`Cod_Turma` ASC),
  CONSTRAINT `Cod_Curso`
    FOREIGN KEY (`Cod_Curso`)
    REFERENCES `DB_faculdade`.`Curso` (`Cod_Curso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_Turma`
    FOREIGN KEY (`Cod_Turma`)
    REFERENCES `DB_faculdade`.`Turma` (`Cod_Turma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Contato_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Contato_Aluno` (
  `Cod_Aluno` INT NOT NULL,
  `Whatsapp` INT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telefone` INT NOT NULL,
  `Telefone_Res` INT NULL,
  PRIMARY KEY (`Cod_Aluno`),
  CONSTRAINT `Cod_Aluno`
    FOREIGN KEY (`Cod_Aluno`)
    REFERENCES `DB_faculdade`.`Aluno` (`Cod_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Endereco_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Endereco_Aluno` (
  `Cod_Aluno` INT NOT NULL,
  `CEP` INT NOT NULL,
  `Rua` VARCHAR(45) NOT NULL,
  `Numero` VARCHAR(45) NOT NULL,
  `Bairro` VARCHAR(45) NOT NULL,
  `Complemento` VARCHAR(45) NULL,
  PRIMARY KEY (`Cod_Aluno`),
  CONSTRAINT `Cod_Aluno`
    FOREIGN KEY (`Cod_Aluno`)
    REFERENCES `DB_faculdade`.`Aluno` (`Cod_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Aluno_Disc`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Aluno_Disc` (
  `Cod_Aluno` INT NOT NULL,
  `Cod_Disciplina` INT NOT NULL,
  PRIMARY KEY (`Cod_Aluno`, `Cod_Disciplina`),
  INDEX `Cod_Disciplina_idx` (`Cod_Disciplina` ASC),
  CONSTRAINT `Cod_Aluno`
    FOREIGN KEY (`Cod_Aluno`)
    REFERENCES `DB_faculdade`.`Aluno` (`Cod_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_Disciplina`
    FOREIGN KEY (`Cod_Disciplina`)
    REFERENCES `DB_faculdade`.`Disciplina` (`Cod_Disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Historico` (
  `Cod_Historico` INT NOT NULL,
  `Cod_Aluno` INT NOT NULL,
  `Frequencia` DECIMAL(10) NOT NULL,
  `Data_Inicio` DATE NOT NULL,
  `Data_Fim` DATE NOT NULL,
  PRIMARY KEY (`Cod_Historico`, `Cod_Aluno`),
  INDEX `Cod_Aluno_idx` (`Cod_Aluno` ASC),
  CONSTRAINT `Cod_Aluno`
    FOREIGN KEY (`Cod_Aluno`)
    REFERENCES `DB_faculdade`.`Aluno` (`Cod_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Disc_Historico`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Disc_Historico` (
  `Cod_Disciplina` INT NOT NULL,
  `Cod_Historico` INT NOT NULL,
  `Notas` DECIMAL(10) NOT NULL,
  `Media` DECIMAL(10) NOT NULL,
  PRIMARY KEY (`Cod_Disciplina`, `Cod_Historico`),
  INDEX `Cod_Historico_idx` (`Cod_Historico` ASC),
  CONSTRAINT `Cod_Disciplina`
    FOREIGN KEY (`Cod_Disciplina`)
    REFERENCES `DB_faculdade`.`Disciplina` (`Cod_Disciplina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Cod_Historico`
    FOREIGN KEY (`Cod_Historico`)
    REFERENCES `DB_faculdade`.`Historico` (`Cod_Historico`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `DB_faculdade`.`Filiacao_Aluno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `DB_faculdade`.`Filiacao_Aluno` (
  `Cod_Aluno` INT NOT NULL,
  `Pai_aluno` VARCHAR(45) NOT NULL,
  `Mae_Aluno` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Cod_Aluno`),
  CONSTRAINT `Cod_Aluno`
    FOREIGN KEY (`Cod_Aluno`)
    REFERENCES `DB_faculdade`.`Aluno` (`Cod_Aluno`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
